kind: Service
apiVersion: v1
metadata:
  name: hello-world-svc
  namespace: hello-world
spec:
  selector:
    app: hello-world
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer
